spring.application.name=worldBuilding

# ===============================
# DB / MySQL
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/worldBuilding
spring.datasource.username=postgres
spring.datasource.password=hisder
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# OpenAPI
# ===============================

springdoc.api-docs.path=/openapi