spring.application.name=worldBuilding

# ===============================
# DB / MySQL
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/world_building
spring.datasource.username=root
spring.datasource.password=hisder
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# OpenAPI
# ===============================

springdoc.api-docs.path=/openapi